# Generated by Django 2.2 on 2019-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0003_auto_20190610_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField()),
                ('category_id', models.ManyToManyField(to='open_food_facts.Category')),
                ('user_id', models.ManyToManyField(to='open_food_facts.User')),
            ],
        ),
    ]
