# Generated by Django 2.2 on 2019-06-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0005_auto_20190616_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='substitute',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='substitute',
            name='score',
            field=models.CharField(max_length=1),
        ),
    ]
