# Generated by Django 2.2 on 2019-07-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0006_auto_20190616_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
