# Generated by Django 2.2 on 2019-07-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0008_auto_20190704_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.FloatField(),
        ),
    ]
