# Generated by Django 2.2 on 2019-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0013_auto_20190713_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='open_food_facts.Category'),
        ),
    ]
