# Generated by Django 2.2 on 2019-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0007_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carbs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='open_food_facts.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, max_length=300, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
