# Generated by Django 2.2 on 2019-07-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0009_auto_20190704_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score_image',
            field=models.ImageField(default='', max_length=300, upload_to=''),
            preserve_default=False,
        ),
    ]
