# Generated by Django 2.2 on 2019-07-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0012_auto_20190713_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(null=True, to='open_food_facts.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
