# Generated by Django 2.2 on 2019-10-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0017_auto_20191025_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
