# Generated by Django 2.2 on 2019-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_food_facts', '0022_auto_20191030_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=400, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
